const express=require("express")
const app=express()
const database=require("./config/database")
const User=require("./models/User")
const authRouter=require("./router/auth")
const todo=require("./router/todo")
const {checkAuth}=require("./middleware/auth")
const bodyParser=require("body-parser")
const cors=require("cors")
database.connect()
app.use(cors())
app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())
app.use("/api/auth",authRouter)
app.use("/api/todo",checkAuth,todo)
// app.get("/",async (req,res)=>{
//     let users=await User.find({}).exec()
//     console.log(users)
//     res.send("hello word")
// })
const port=process.env.port || "5000"
app.listen(port,()=>{
    console.log("server listen at port 5000...")
})